grpc:
  host: 'server.p2pderivatives.io:443'
  secure: true
  certificatePath: ./p2pderivatives.io.crt
oracle:
  initialOracles:
    - name: 'P2PDerivatives'
      uri: 'https://oracle.p2pderivatives.io'
